# Generated by Django 5.0.6 on 2024-05-23 11:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_friends_accepted_remove_friends_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', max_length=10)),
                ('chat_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_friend', to='main.friends')),
                ('chat_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_as_user', to='main.friends')),
            ],
        ),
    ]
