# Generated by Django 5.0.6 on 2024-05-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat_user',
            new_name='chat_between',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='chat_friend',
        ),
    ]
