# Generated by Django 5.0.6 on 2024-05-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_chat_user_chat_chat_between_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_name',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
