# Generated by Django 5.0.6 on 2024-05-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_chat_message_remove_chat_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
